/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: pnpm content:manifest
 *
 * This file provides statically bundled content manifest data.
 * No runtime fs dependency - works in dev and production builds.
 */

import type { ContentType, Locale } from '@/types/content.types';

export interface ContentEntry {
  type: ContentType;
  locale: Locale;
  slug: string;
  extension: string;
  filePath: string;
  relativePath: string;
}

export interface ContentManifest {
  entries: ContentEntry[];
  byKey: Record<string, ContentEntry>;
}

export const CONTENT_MANIFEST: ContentManifest = {
  entries: [
  {
    "type": "posts",
    "locale": "en",
    "slug": "welcome",
    "extension": ".mdx",
    "filePath": "/content/posts/en/welcome.mdx",
    "relativePath": "content/posts/en/welcome.mdx"
  },
  {
    "type": "posts",
    "locale": "zh",
    "slug": "welcome",
    "extension": ".mdx",
    "filePath": "/content/posts/zh/welcome.mdx",
    "relativePath": "content/posts/zh/welcome.mdx"
  },
  {
    "type": "pages",
    "locale": "en",
    "slug": "about",
    "extension": ".mdx",
    "filePath": "/content/pages/en/about.mdx",
    "relativePath": "content/pages/en/about.mdx"
  },
  {
    "type": "pages",
    "locale": "en",
    "slug": "bending-machines",
    "extension": ".mdx",
    "filePath": "/content/pages/en/bending-machines.mdx",
    "relativePath": "content/pages/en/bending-machines.mdx"
  },
  {
    "type": "pages",
    "locale": "en",
    "slug": "contact",
    "extension": ".mdx",
    "filePath": "/content/pages/en/contact.mdx",
    "relativePath": "content/pages/en/contact.mdx"
  },
  {
    "type": "pages",
    "locale": "en",
    "slug": "oem-custom-manufacturing",
    "extension": ".mdx",
    "filePath": "/content/pages/en/oem-custom-manufacturing.mdx",
    "relativePath": "content/pages/en/oem-custom-manufacturing.mdx"
  },
  {
    "type": "pages",
    "locale": "en",
    "slug": "privacy",
    "extension": ".mdx",
    "filePath": "/content/pages/en/privacy.mdx",
    "relativePath": "content/pages/en/privacy.mdx"
  },
  {
    "type": "pages",
    "locale": "en",
    "slug": "terms",
    "extension": ".mdx",
    "filePath": "/content/pages/en/terms.mdx",
    "relativePath": "content/pages/en/terms.mdx"
  },
  {
    "type": "pages",
    "locale": "zh",
    "slug": "about",
    "extension": ".mdx",
    "filePath": "/content/pages/zh/about.mdx",
    "relativePath": "content/pages/zh/about.mdx"
  },
  {
    "type": "pages",
    "locale": "zh",
    "slug": "bending-machines",
    "extension": ".mdx",
    "filePath": "/content/pages/zh/bending-machines.mdx",
    "relativePath": "content/pages/zh/bending-machines.mdx"
  },
  {
    "type": "pages",
    "locale": "zh",
    "slug": "contact",
    "extension": ".mdx",
    "filePath": "/content/pages/zh/contact.mdx",
    "relativePath": "content/pages/zh/contact.mdx"
  },
  {
    "type": "pages",
    "locale": "zh",
    "slug": "oem-custom-manufacturing",
    "extension": ".mdx",
    "filePath": "/content/pages/zh/oem-custom-manufacturing.mdx",
    "relativePath": "content/pages/zh/oem-custom-manufacturing.mdx"
  },
  {
    "type": "pages",
    "locale": "zh",
    "slug": "privacy",
    "extension": ".mdx",
    "filePath": "/content/pages/zh/privacy.mdx",
    "relativePath": "content/pages/zh/privacy.mdx"
  },
  {
    "type": "pages",
    "locale": "zh",
    "slug": "terms",
    "extension": ".mdx",
    "filePath": "/content/pages/zh/terms.mdx",
    "relativePath": "content/pages/zh/terms.mdx"
  }
],
  byKey: {
  "posts/en/welcome": {
    "type": "posts",
    "locale": "en",
    "slug": "welcome",
    "extension": ".mdx",
    "filePath": "/content/posts/en/welcome.mdx",
    "relativePath": "content/posts/en/welcome.mdx"
  },
  "posts/zh/welcome": {
    "type": "posts",
    "locale": "zh",
    "slug": "welcome",
    "extension": ".mdx",
    "filePath": "/content/posts/zh/welcome.mdx",
    "relativePath": "content/posts/zh/welcome.mdx"
  },
  "pages/en/about": {
    "type": "pages",
    "locale": "en",
    "slug": "about",
    "extension": ".mdx",
    "filePath": "/content/pages/en/about.mdx",
    "relativePath": "content/pages/en/about.mdx"
  },
  "pages/en/bending-machines": {
    "type": "pages",
    "locale": "en",
    "slug": "bending-machines",
    "extension": ".mdx",
    "filePath": "/content/pages/en/bending-machines.mdx",
    "relativePath": "content/pages/en/bending-machines.mdx"
  },
  "pages/en/contact": {
    "type": "pages",
    "locale": "en",
    "slug": "contact",
    "extension": ".mdx",
    "filePath": "/content/pages/en/contact.mdx",
    "relativePath": "content/pages/en/contact.mdx"
  },
  "pages/en/oem-custom-manufacturing": {
    "type": "pages",
    "locale": "en",
    "slug": "oem-custom-manufacturing",
    "extension": ".mdx",
    "filePath": "/content/pages/en/oem-custom-manufacturing.mdx",
    "relativePath": "content/pages/en/oem-custom-manufacturing.mdx"
  },
  "pages/en/privacy": {
    "type": "pages",
    "locale": "en",
    "slug": "privacy",
    "extension": ".mdx",
    "filePath": "/content/pages/en/privacy.mdx",
    "relativePath": "content/pages/en/privacy.mdx"
  },
  "pages/en/terms": {
    "type": "pages",
    "locale": "en",
    "slug": "terms",
    "extension": ".mdx",
    "filePath": "/content/pages/en/terms.mdx",
    "relativePath": "content/pages/en/terms.mdx"
  },
  "pages/zh/about": {
    "type": "pages",
    "locale": "zh",
    "slug": "about",
    "extension": ".mdx",
    "filePath": "/content/pages/zh/about.mdx",
    "relativePath": "content/pages/zh/about.mdx"
  },
  "pages/zh/bending-machines": {
    "type": "pages",
    "locale": "zh",
    "slug": "bending-machines",
    "extension": ".mdx",
    "filePath": "/content/pages/zh/bending-machines.mdx",
    "relativePath": "content/pages/zh/bending-machines.mdx"
  },
  "pages/zh/contact": {
    "type": "pages",
    "locale": "zh",
    "slug": "contact",
    "extension": ".mdx",
    "filePath": "/content/pages/zh/contact.mdx",
    "relativePath": "content/pages/zh/contact.mdx"
  },
  "pages/zh/oem-custom-manufacturing": {
    "type": "pages",
    "locale": "zh",
    "slug": "oem-custom-manufacturing",
    "extension": ".mdx",
    "filePath": "/content/pages/zh/oem-custom-manufacturing.mdx",
    "relativePath": "content/pages/zh/oem-custom-manufacturing.mdx"
  },
  "pages/zh/privacy": {
    "type": "pages",
    "locale": "zh",
    "slug": "privacy",
    "extension": ".mdx",
    "filePath": "/content/pages/zh/privacy.mdx",
    "relativePath": "content/pages/zh/privacy.mdx"
  },
  "pages/zh/terms": {
    "type": "pages",
    "locale": "zh",
    "slug": "terms",
    "extension": ".mdx",
    "filePath": "/content/pages/zh/terms.mdx",
    "relativePath": "content/pages/zh/terms.mdx"
  }
},
} as const;
