/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: pnpm content:manifest
 *
 * This file provides static import maps for MDX content.
 * To update, add/remove/rename content files and re-run the generator.
 */

import type { ComponentType } from 'react';

export interface MDXContentModule {
  default: ComponentType;
  frontmatter?: Record<string, unknown>;
}

type ContentImporter = () => Promise<MDXContentModule>;

export const postImporters: Record<string, Record<string, ContentImporter>> = {
  en: {
    'welcome': () => import('@content/posts/en/welcome.mdx'),
  },
  zh: {
    'welcome': () => import('@content/posts/zh/welcome.mdx'),
  },
};

export const pageImporters: Record<string, Record<string, ContentImporter>> = {
  en: {
    'about': () => import('@content/pages/en/about.mdx'),
    'faq': () => import('@content/pages/en/faq.mdx'),
    'privacy': () => import('@content/pages/en/privacy.mdx'),
    'terms': () => import('@content/pages/en/terms.mdx'),
  },
  zh: {
    'about': () => import('@content/pages/zh/about.mdx'),
    'faq': () => import('@content/pages/zh/faq.mdx'),
    'privacy': () => import('@content/pages/zh/privacy.mdx'),
    'terms': () => import('@content/pages/zh/terms.mdx'),
  },
};

export const productImporters: Record<string, Record<string, ContentImporter>> = {
  en: {
    'full-auto-bending-machine': () => import('@content/products/en/full-auto-bending-machine.mdx'),
    'petg-pneumatic-tube': () => import('@content/products/en/petg-pneumatic-tube.mdx'),
    'pvc-conduit-bend': () => import('@content/products/en/pvc-conduit-bend.mdx'),
    'sample-product': () => import('@content/products/en/sample-product.mdx'),
    'semi-auto-bending-machine': () => import('@content/products/en/semi-auto-bending-machine.mdx'),
  },
  zh: {
    'full-auto-bending-machine': () => import('@content/products/zh/full-auto-bending-machine.mdx'),
    'petg-pneumatic-tube': () => import('@content/products/zh/petg-pneumatic-tube.mdx'),
    'pvc-conduit-bend': () => import('@content/products/zh/pvc-conduit-bend.mdx'),
    'sample-product': () => import('@content/products/zh/sample-product.mdx'),
    'semi-auto-bending-machine': () => import('@content/products/zh/semi-auto-bending-machine.mdx'),
  },
};
