/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: pnpm content:manifest
 *
 * This file provides static import maps for MDX content.
 * To update, add/remove/rename content files and re-run the generator.
 */

import type { ComponentType } from 'react';

export interface MDXContentModule {
  default: ComponentType;
  frontmatter?: Record<string, unknown>;
}

type ContentImporter = () => Promise<MDXContentModule>;

export const postImporters: Record<string, Record<string, ContentImporter>> = {
  en: {
    'welcome': () => import('@content/posts/en/welcome.mdx'),
  },
  zh: {
    'welcome': () => import('@content/posts/zh/welcome.mdx'),
  },
};

export const pageImporters: Record<string, Record<string, ContentImporter>> = {
  en: {
    'about': () => import('@content/pages/en/about.mdx'),
    'bending-machines': () => import('@content/pages/en/bending-machines.mdx'),
    'contact': () => import('@content/pages/en/contact.mdx'),
    'oem-custom-manufacturing': () => import('@content/pages/en/oem-custom-manufacturing.mdx'),
    'privacy': () => import('@content/pages/en/privacy.mdx'),
    'product-market': () => import('@content/pages/en/product-market.mdx'),
    'terms': () => import('@content/pages/en/terms.mdx'),
  },
  zh: {
    'about': () => import('@content/pages/zh/about.mdx'),
    'bending-machines': () => import('@content/pages/zh/bending-machines.mdx'),
    'contact': () => import('@content/pages/zh/contact.mdx'),
    'oem-custom-manufacturing': () => import('@content/pages/zh/oem-custom-manufacturing.mdx'),
    'privacy': () => import('@content/pages/zh/privacy.mdx'),
    'product-market': () => import('@content/pages/zh/product-market.mdx'),
    'terms': () => import('@content/pages/zh/terms.mdx'),
  },
};

export const productImporters: Record<string, Record<string, ContentImporter>> = {
  en: {
  },
  zh: {
  },
};
